# Generated by Django 4.2 on 2023-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_gram', models.FloatField()),
                ('protein_per_gram', models.FloatField()),
                ('carbs_per_gram', models.FloatField()),
                ('fats_per_gram', models.FloatField()),
            ],
        ),
    ]
