# Generated by Django 4.2 on 2023-04-19 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
