# Generated by Django 4.2 on 2023-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_userhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
