# Generated by Django 4.2 on 2023-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_userhistory_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='imageURL',
            field=models.URLField(null=True),
        ),
    ]
